# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 46173287630ec30a03c7f64ff2a2aa310f4e3640b7ccf342a6ae1592faed40dd8e6b5d0529235e6adc5e275ce20ca931e19ea3eee854f1a7420434421bba130d

test:
  secret_key_base: b4cc3c3190341f62faf0dfeed8cc4a984da13206cab18099fbcfd2559e38a011594f171ae9b963e507a43479dc1d05cf3c7edfe5f40ed66bda99ad9617568016

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
